"""Миграция 12

Revision ID: 2e4a622dbd9d
Revises: 4bbcc9a2faf2
Create Date: 2025-01-09 11:11:01.156840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4a622dbd9d'
down_revision = '4bbcc9a2faf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_file_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('original_file_name')

    # ### end Alembic commands ###
