"""Миграция 3

Revision ID: 3bc2b8c1f22d
Revises: fda98463d61a
Create Date: 2025-01-07 09:28:35.087901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc2b8c1f22d'
down_revision = 'fda98463d61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)

    # ### end Alembic commands ###
