"""Миграция 11

Revision ID: 4bbcc9a2faf2
Revises: 89f34d27f8fd
Create Date: 2025-01-08 16:19:14.216997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbcc9a2faf2'
down_revision = '89f34d27f8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_participants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_participants_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_task_participants_task_id_user_id', ['task_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_participants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_participants_user_id'))
        batch_op.drop_index('ix_task_participants_task_id_user_id')
        batch_op.drop_index(batch_op.f('ix_task_participants_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_participants_created_at'))

    op.drop_table('task_participants')
    # ### end Alembic commands ###
