"""Миграция 6

Revision ID: 66487928f2da
Revises: c50b58fc3fc1
Create Date: 2025-01-07 18:47:03.581411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66487928f2da'
down_revision = 'c50b58fc3fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=64), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False))
        batch_op.drop_column('color')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
