"""Ворклог 6

Revision ID: 94ab8b586a05
Revises: dd00aa9f89fb
Create Date: 2025-01-14 12:28:01.744692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94ab8b586a05'
down_revision = 'dd00aa9f89fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_shift', schema=None) as batch_op:
        batch_op.alter_column('from_on',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('to',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_shift', schema=None) as batch_op:
        batch_op.alter_column('to',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               existing_nullable=False)
        batch_op.alter_column('from_on',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
