"""Ворклог 7

Revision ID: bcfba01a92e6
Revises: 94ab8b586a05
Create Date: 2025-01-14 12:32:30.204257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfba01a92e6'
down_revision = '94ab8b586a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('needed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_shift', schema=None) as batch_op:
        batch_op.drop_column('needed')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
