"""Миграция 9

Revision ID: c1854c62f0c2
Revises: e5e21c90bd9b
Create Date: 2025-01-08 12:29:27.249066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1854c62f0c2'
down_revision = 'e5e21c90bd9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_platform_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_platform_id'), ['task_platform_id'], unique=False)
        batch_op.create_index('ix_tasks_task_platform_id_deadline', ['task_platform_id', 'deadline'], unique=False)

    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index('ix_checklist_task_id_created_at', ['task_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_task_id'), ['task_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_comments_task_id_user_id_created_at', ['task_id', 'user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_files_task_id_uploaded_by', ['task_id', 'uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_reports_task_id_created_by', ['task_id', 'created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_task_id_created_by')
        batch_op.drop_index(batch_op.f('ix_reports_task_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_by'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploaded_by'))
        batch_op.drop_index('ix_files_task_id_uploaded_by')
        batch_op.drop_index(batch_op.f('ix_files_task_id'))
        batch_op.drop_index(batch_op.f('ix_files_created_at'))

    op.drop_table('files')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index('ix_comments_task_id_user_id_created_at')
        batch_op.drop_index(batch_op.f('ix_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))

    op.drop_table('comments')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_task_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_created_at'))
        batch_op.drop_index('ix_checklist_task_id_created_at')

    op.drop_table('checklists')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_task_platform_id_deadline')
        batch_op.drop_index(batch_op.f('ix_tasks_task_platform_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_department_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deadline'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))

    op.drop_table('tasks')
    # ### end Alembic commands ###
