"""Миграция 5

Revision ID: c50b58fc3fc1
Revises: 3e8cef74ef4e
Create Date: 2025-01-07 15:10:41.509169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c50b58fc3fc1'
down_revision = '3e8cef74ef4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaxta', schema=None) as batch_op:
        batch_op.alter_column('start_day',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('end_day',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaxta', schema=None) as batch_op:
        batch_op.alter_column('end_day',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
        batch_op.alter_column('start_day',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
