"""Миграция 8

Revision ID: e5e21c90bd9b
Revises: 95277c457667
Create Date: 2025-01-07 19:26:28.017465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e21c90bd9b'
down_revision = '95277c457667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('end_day')
        batch_op.drop_column('start_day')

    # ### end Alembic commands ###
