"""Ворклог 4

Revision ID: f466e0954bcf
Revises: 60aa60d7ae52
Create Date: 2025-01-11 16:39:00.062977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f466e0954bcf'
down_revision = '60aa60d7ae52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
